Update main.yml
Stop Incoming/Outgoing info

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,49 +1,49 @@
-# This is a basic workflow to help you get started with Actions
+# # This is a basic workflow to help you get started with Actions
 
-name: Execució meteo python file
+# name: Execució meteo python file
 
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  schedule:
-  # He posat cada dos minuts per fer les proves
-    - cron: '59 23 * * *' # Amb '59 23 * * *' podem fer que  s'executi cada dia a les 23:59 UTC
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+# # Controls when the workflow will run
+# on:
+#   # Triggers the workflow on push or pull request events but only for the "main" branch
+#   schedule:
+#   # He posat cada dos minuts per fer les proves
+#     - cron: '59 23 * * *' # Amb '59 23 * * *' podem fer que  s'executi cada dia a les 23:59 UTC
+#   # Allows you to run this workflow manually from the Actions tab
+#   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# jobs:
+#   # This workflow contains a single job called "build"
+#   build:
+#     # The type of runner that the job will run on
+#     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Clonar el repositori
-        uses: actions/checkout@v4
+#     # Steps represent a sequence of tasks that will be executed as part of the job
+#     steps:
+#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+#       - name: Clonar el repositori
+#         uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
-      - name: Configurar Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.11'
+#       # Runs a single command using the runners shell
+#       - name: Configurar Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: '3.11'
       
-      - name: Instal·lar Dependències
-        run: |
-          python -m pip install --upgrade pip
-          pip install pytest
-          pip install openmeteo-requests
-          pip install requests-cache retry-requests numpy pandas
+#       - name: Instal·lar Dependències
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install pytest
+#           pip install openmeteo-requests
+#           pip install requests-cache retry-requests numpy pandas
 
-      - name: Executar el script
-        run: python resultatsAPI.py
+#       - name: Executar el script
+#         run: python resultatsAPI.py
 
-      - name: Fer commit del .json generat
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add dades_json/*.json
-          git commit -m "Afegit arxius JSON generats automàticament" || echo "No hi ha canvis per commitejar"
-          git push
+#       - name: Fer commit del .json generat
+#         run: |
+#           git config user.name "github-actions[bot]"
+#           git config user.email "github-actions[bot]@users.noreply.github.com"
+#           git add dades_json/*.json
+#           git commit -m "Afegit arxius JSON generats automàticament" || echo "No hi ha canvis per commitejar"
+#           git push
